verbosity = 2

[server]
# exit session if no requests were received during given period in seconds
# works only in unix sockets mode (-s/--session)
# set to 0 to disable
timeout = 1800 # seconds = 30 minutes

[language.javascript]
filetypes = ["javascript"]
roots = ["package.json"]
command = "/Users/mattschick/.nodenv/shims/typescript-language-server"
args = ["--stdio"]

